<?php
/*
* @Created by: HSS
* @Author	 : nguyenduypt86@gmail.com
* @Date 	 : 06/2014
* @Version	 : 1.0
*/
/**
 * Implements hook_menu().
 */
function HSSCore_menu() {
    $items = array();
	$items['trang-chu'] = array(
        'title' => t('Trang chủ'),
        'page callback' => 'page_default',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items["admin/admincp"] = array(
        "title" => t("Trang chủ quản trị"),
        "description" => t("Administration"),
        'page callback' => 'admin_redirect',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
	$items["admincp"] = array(
        "title" => t("Trang chủ quản trị"),
        "description" => t("Administration"),
        'page callback' => 'router_page',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items["page-403"] = array(
        "title" => t("page access denied"),
        "description" => t("page access denied"),
        'page callback' => 'page_403',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items["page-404"] = array(
        "title" => t("page not found"),
        "description" => t("page not found"),
        'page callback' => 'page_404',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
  return $items;
}

function HSSCore_block_info() {

    $blocks['admin-header'] = array(
        'info' => t('Block admin header'),
        'status'	=> TRUE,
        'region'	=> 'header',
        'weight'	=> 0,
        'visibility' => 1,
    );

    $blocks['admin-left'] = array(
        'info' => t('Block admin left'),
        'status'	=> TRUE,
        'region'	=> 'left',
        'weight'	=> 0,
        'visibility' => 1,
    );

	 $blocks['admin-content'] = array(
        'info' => t('Block admin content'),
        'status'	=> TRUE,
        'region'	=> 'content',
        'weight'	=> 0,
        'visibility' => 1,
    );

    $blocks['admin-footer'] = array(
        'info' => t('Block admin footer'),
        'status'	=> TRUE,
        'region'	=> 'footer',
        'weight'	=> 0,
        'visibility' => 1,
    );

    return $blocks;
}

function HSSCore_theme() {
    return array(

		'admin-header' => array(
            'template' => 'View/tpl/admin/admin-header'
        ),
        'admin-left' => array(
            'template' => 'View/tpl/admin/admin-left'
        ),
      	'admin-content' => array(
            'template' => 'View/tpl/admin/admin-content'
        ),
        'admin-footer' => array(
            'template' => 'View/tpl/admin/admin-footer'
        ),

		'page_403' => array(
            'template' => 'View/tpl/page_403'
        ),

        'page_404' => array(
            'template' => 'View/tpl/page_404'
        )
    );
}

/**
 * Implements hook_block_view().
 */
function HSSCore_block_view($delta='') {
    $block = array();
    switch ($delta) {
        case 'admin-header':
            $block['subject'] = t('Block admin header');
            $block['content'] = blockAdminHeader();
            break;

		case 'admin-left':
            $block['subject'] = t('Block admin left');
            $block['content'] = blockAdminLeft();
            break;

        case 'admin-content':
            $block['subject'] = t('Block admin content');
            $block['content'] = blockAdminContent();
            break;

        case 'admin-footer':
            $block['subject'] = t('Block admin footer');
            $block['content'] = blockAdminFooter();
            break;
    }

    return $block;
}

/**
 * Implements hook_permission().
 */
function HSSCore_permission() {
  return array(
    'access protected HSS Core' => array(
      'title' => t('Access protected HSS Core'),
    ),
  );
}
/**
 * Implementation of hook_init().
 */
require_once 'autoload.php';

function HSSCore_init(){
	drupal_add_library('system', 'ui.dialog');
	drupal_add_library('system', 'ui.datepicker');

	$files = array(
		'View/css/HSSCore.css',
		'View/js/jquery.alerts.js',
		//'View/js/jquery.lazyload.js',
	);
	clsLoader::load('HSSCore', $files);
	$uri = request_uri();
	if(preg_match("/(\/admincp)/", $uri)!=0){
		$files_admin = array(
			'Controller/admin_default_page.php',
			'View/css/admin.css',
			'View/js/admin.js',
			//'View/js/ckeditor/ckeditor.js',
			//'View/js/ckeditor/config.js',
			'View/js/jquery.html5uploader.min.js',
			'View/js/upload_files.js',
		);
		clsLoader::load('HSSCore', $files_admin);
    }
}

function page_default(){
	drupal_set_title('Mua bán bất động sản');
	return '';
}
function page_403(){

   $view = theme('page_403');
	return $view;
}
function page_404(){

	$view = theme('page_404');
	return $view;
}
function admin_redirect(){
    global $base_url;
    drupal_goto($base_url.'/admincp');
}